name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: tecnophille
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake file
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate snake contribution graph"
          add: "dist/github-contribution-grid-snake.svg"
